'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

' Original file name:
' Generation date: 8/1/2010 5:29:57 PM

Imports Microsoft.VisualBasic
Imports System
Namespace DevExpress.Calendar.Model

	''' <summary>
	''' There are no comments for Service in the schema.
	''' </summary>
	Partial Public Class Service
		Inherits System.Data.Services.Client.DataServiceContext
		''' <summary>
		''' Initialize a new Service object.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub New(ByVal serviceRoot As Global.System.Uri)
			MyBase.New(serviceRoot)
			Me.ResolveName = New Global.System.Func(Of Global.System.Type, String)(AddressOf Me.ResolveNameFromType)
			Me.ResolveType = New Global.System.Func(Of String, Global.System.Type)(AddressOf Me.ResolveTypeFromName)
			Me.OnContextCreated()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		''' <summary>
		''' Since the namespace configured for this service reference
		''' in Visual Studio is different from the one indicated in the
		''' server schema, use type-mappers to map between the two.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
			If typeName.StartsWith("DevExpress.Calendar.Model", Global.System.StringComparison.Ordinal) Then
				Return Me.GetType().Assembly.GetType(String.Concat("DevExpress.Calendar.Model", typeName.Substring(25)), False)
			End If
			Return Nothing
		End Function
		''' <summary>
		''' Since the namespace configured for this service reference
		''' in Visual Studio is different from the one indicated in the
		''' server schema, use type-mappers to map between the two.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
			If clientType.Namespace.Equals("DevExpress.Calendar.Model", Global.System.StringComparison.Ordinal) Then
				Return String.Concat("DevExpress.Calendar.Model.", clientType.Name)
			End If
			Return Nothing
		End Function
		''' <summary>
		''' There are no comments for Resources in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Resources() As Global.System.Data.Services.Client.DataServiceQuery(Of Resource)
			Get
				If (Me._Resources Is Nothing) Then
					Me._Resources = MyBase.CreateQuery(Of Resource)("Resources")
				End If
				Return Me._Resources
			End Get
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Resources As Global.System.Data.Services.Client.DataServiceQuery(Of Resource)
		''' <summary>
		''' There are no comments for Appointments in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public ReadOnly Property Appointments() As Global.System.Data.Services.Client.DataServiceQuery(Of Appointment)
			Get
				If (Me._Appointments Is Nothing) Then
					Me._Appointments = MyBase.CreateQuery(Of Appointment)("Appointments")
				End If
				Return Me._Appointments
			End Get
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Appointments As Global.System.Data.Services.Client.DataServiceQuery(Of Appointment)
		''' <summary>
		''' There are no comments for Resources in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToResources(ByVal resource As Resource)
			MyBase.AddObject("Resources", resource)
		End Sub
		''' <summary>
		''' There are no comments for Appointments in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Sub AddToAppointments(ByVal appointment As Appointment)
			MyBase.AddObject("Appointments", appointment)
		End Sub
	End Class
	''' <summary>
	''' There are no comments for DevExpress.Calendar.Model.Resource in the schema.
	''' </summary>
	''' <KeyProperties>
	''' ID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")> _
	Partial Public Class Resource
		''' <summary>
		''' Create a new Resource object.
		''' </summary>
		''' <param name="ID">Initial value of ID.</param>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateResource(ByVal ID As Global.System.Guid) As Resource
			Dim resource As New Resource()
			resource.ID = ID
			Return resource
		End Function
		''' <summary>
		''' There are no comments for Property ID in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ID() As Global.System.Guid
			Get
				Return Me._ID
			End Get
			Set(ByVal value As System.Guid)
				Me.OnIDChanging(value)
				Me._ID = value
				Me.OnIDChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ID As Global.System.Guid
		Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Email in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Email() As String
			Get
				Return Me._Email
			End Get
			Set(ByVal value As String)
				Me.OnEmailChanging(value)
				Me._Email = value
				Me.OnEmailChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Email As String
		Partial Private Sub OnEmailChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnEmailChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UserName in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property UserName() As String
			Get
				Return Me._UserName
			End Get
			Set(ByVal value As String)
				Me.OnUserNameChanging(value)
				Me._UserName = value
				Me.OnUserNameChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _UserName As String
		Partial Private Sub OnUserNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnUserNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Name in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Name() As String
			Get
				Return Me._Name
			End Get
			Set(ByVal value As String)
				Me.OnNameChanging(value)
				Me._Name = value
				Me.OnNameChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Name As String
		Partial Private Sub OnNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Appointments in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Appointments() As Global.System.Collections.ObjectModel.Collection(Of Appointment)
			Get
				Return Me._Appointments
			End Get
			Set(ByVal value As System.Collections.ObjectModel.Collection(Of Appointment))
				If (value IsNot Nothing) Then
					Me._Appointments = value
				End If
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Appointments As New Global.System.Collections.ObjectModel.Collection(Of Appointment)()
	End Class
	''' <summary>
	''' There are no comments for DevExpress.Calendar.Model.Appointment in the schema.
	''' </summary>
	''' <KeyProperties>
	''' ID
	''' </KeyProperties>
	<Global.System.Data.Services.Common.DataServiceKeyAttribute("ID")> _
	Partial Public Class Appointment
		''' <summary>
		''' Create a new Appointment object.
		''' </summary>
		''' <param name="ID">Initial value of ID.</param>
		''' <param name="isAllDay">Initial value of IsAllDay.</param>
		''' <param name="label">Initial value of Label.</param>
		''' <param name="completionStatus">Initial value of CompletionStatus.</param>
		''' <param name="start">Initial value of Start.</param>
		''' <param name="finish">Initial value of Finish.</param>
		''' <param name="status">Initial value of Status.</param>
		''' <param name="itemType">Initial value of ItemType.</param>
		''' <param name="appointmentType">Initial value of AppointmentType.</param>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Shared Function CreateAppointment(ByVal ID As Global.System.Guid, ByVal isAllDay As Boolean, ByVal label As Integer, ByVal completionStatus As Integer, ByVal start As Global.System.DateTime, ByVal finish As Global.System.DateTime, ByVal status As Integer, ByVal itemType As Integer, ByVal appointmentType As Integer) As Appointment
			Dim appointment As New Appointment()
			appointment.ID = ID
			appointment.IsAllDay = isAllDay
			appointment.Label = label
			appointment.CompletionStatus = completionStatus
			appointment.Start = start
			appointment.Finish = finish
			appointment.Status = status
			appointment.ItemType = itemType
			appointment.AppointmentType = appointmentType
			Return appointment
		End Function
		''' <summary>
		''' There are no comments for Property ID in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ID() As Global.System.Guid
			Get
				Return Me._ID
			End Get
			Set(ByVal value As System.Guid)
				Me.OnIDChanging(value)
				Me._ID = value
				Me.OnIDChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ID As Global.System.Guid
		Partial Private Sub OnIDChanging(ByVal value As Global.System.Guid)
		End Sub
		Partial Private Sub OnIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property IsAllDay in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property IsAllDay() As Boolean
			Get
				Return Me._IsAllDay
			End Get
			Set(ByVal value As Boolean)
				Me.OnIsAllDayChanging(value)
				Me._IsAllDay = value
				Me.OnIsAllDayChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _IsAllDay As Boolean
		Partial Private Sub OnIsAllDayChanging(ByVal value As Boolean)
		End Sub
		Partial Private Sub OnIsAllDayChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Description in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Description() As String
			Get
				Return Me._Description
			End Get
			Set(ByVal value As String)
				Me.OnDescriptionChanging(value)
				Me._Description = value
				Me.OnDescriptionChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Description As String
		Partial Private Sub OnDescriptionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnDescriptionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Notes in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Notes() As String
			Get
				Return Me._Notes
			End Get
			Set(ByVal value As String)
				Me.OnNotesChanging(value)
				Me._Notes = value
				Me.OnNotesChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Notes As String
		Partial Private Sub OnNotesChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnNotesChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Label in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Label() As Integer
			Get
				Return Me._Label
			End Get
			Set(ByVal value As Integer)
				Me.OnLabelChanging(value)
				Me._Label = value
				Me.OnLabelChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Label As Integer
		Partial Private Sub OnLabelChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnLabelChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Location in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Location() As String
			Get
				Return Me._Location
			End Get
			Set(ByVal value As String)
				Me.OnLocationChanging(value)
				Me._Location = value
				Me.OnLocationChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Location As String
		Partial Private Sub OnLocationChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnLocationChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Recurrence in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Recurrence() As String
			Get
				Return Me._Recurrence
			End Get
			Set(ByVal value As String)
				Me.OnRecurrenceChanging(value)
				Me._Recurrence = value
				Me.OnRecurrenceChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Recurrence As String
		Partial Private Sub OnRecurrenceChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnRecurrenceChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Reminder in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Reminder() As String
			Get
				Return Me._Reminder
			End Get
			Set(ByVal value As String)
				Me.OnReminderChanging(value)
				Me._Reminder = value
				Me.OnReminderChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Reminder As String
		Partial Private Sub OnReminderChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnReminderChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CompletionStatus in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property CompletionStatus() As Integer
			Get
				Return Me._CompletionStatus
			End Get
			Set(ByVal value As Integer)
				Me.OnCompletionStatusChanging(value)
				Me._CompletionStatus = value
				Me.OnCompletionStatusChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _CompletionStatus As Integer
		Partial Private Sub OnCompletionStatusChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnCompletionStatusChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Start in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Start() As Global.System.DateTime
			Get
				Return Me._Start
			End Get
			Set(ByVal value As System.DateTime)
				Me.OnStartChanging(value)
				Me._Start = value
				Me.OnStartChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Start As Global.System.DateTime
		Partial Private Sub OnStartChanging(ByVal value As Global.System.DateTime)
		End Sub
		Partial Private Sub OnStartChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Finish in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Finish() As Global.System.DateTime
			Get
				Return Me._Finish
			End Get
			Set(ByVal value As System.DateTime)
				Me.OnFinishChanging(value)
				Me._Finish = value
				Me.OnFinishChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Finish As Global.System.DateTime
		Partial Private Sub OnFinishChanging(ByVal value As Global.System.DateTime)
		End Sub
		Partial Private Sub OnFinishChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Status in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Status() As Integer
			Get
				Return Me._Status
			End Get
			Set(ByVal value As Integer)
				Me.OnStatusChanging(value)
				Me._Status = value
				Me.OnStatusChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Status As Integer
		Partial Private Sub OnStatusChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnStatusChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Subject in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Subject() As String
			Get
				Return Me._Subject
			End Get
			Set(ByVal value As String)
				Me.OnSubjectChanging(value)
				Me._Subject = value
				Me.OnSubjectChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Subject As String
		Partial Private Sub OnSubjectChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnSubjectChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ItemType in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property ItemType() As Integer
			Get
				Return Me._ItemType
			End Get
			Set(ByVal value As Integer)
				Me.OnItemTypeChanging(value)
				Me._ItemType = value
				Me.OnItemTypeChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _ItemType As Integer
		Partial Private Sub OnItemTypeChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnItemTypeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property AppointmentType in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property AppointmentType() As Integer
			Get
				Return Me._AppointmentType
			End Get
			Set(ByVal value As Integer)
				Me.OnAppointmentTypeChanging(value)
				Me._AppointmentType = value
				Me.OnAppointmentTypeChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _AppointmentType As Integer
		Partial Private Sub OnAppointmentTypeChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnAppointmentTypeChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property AssignedTo in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property AssignedTo() As Global.System.Guid?
			Get
				Return Me._AssignedTo
			End Get
			Set(ByVal value? As System.Guid)
				Me.OnAssignedToChanging(value)
				Me._AssignedTo = value
				Me.OnAssignedToChanged()
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _AssignedTo? As Global.System.Guid
		Partial Private Sub OnAssignedToChanging(ByVal value? As Global.System.Guid)
		End Sub
		Partial Private Sub OnAssignedToChanged()
		End Sub
		''' <summary>
		''' There are no comments for Resource in the schema.
		''' </summary>
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Public Property Resource() As Resource
			Get
				Return Me._Resource
			End Get
			Set(ByVal value As Resource)
				Me._Resource = value
			End Set
		End Property
		<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")> _
		Private _Resource As Resource
	End Class
End Namespace
