//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8/1/2010 5:29:57 PM
namespace DevExpress.Calendar.Model
{
    
    /// <summary>
    /// There are no comments for Service in the schema.
    /// </summary>
    public partial class Service : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Service object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Service(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("DevExpress.Calendar.Model", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("DevExpress.Calendar.Model", typeName.Substring(25)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DevExpress.Calendar.Model", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DevExpress.Calendar.Model.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Resources in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Resource> Resources
        {
            get
            {
                if ((this._Resources == null))
                {
                    this._Resources = base.CreateQuery<Resource>("Resources");
                }
                return this._Resources;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Resource> _Resources;
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Appointment> Appointments
        {
            get
            {
                if ((this._Appointments == null))
                {
                    this._Appointments = base.CreateQuery<Appointment>("Appointments");
                }
                return this._Appointments;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Appointment> _Appointments;
        /// <summary>
        /// There are no comments for Resources in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResources(Resource resource)
        {
            base.AddObject("Resources", resource);
        }
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppointments(Appointment appointment)
        {
            base.AddObject("Appointments", appointment);
        }
    }
    /// <summary>
    /// There are no comments for DevExpress.Calendar.Model.Resource in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Resource
    {
        /// <summary>
        /// Create a new Resource object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Resource CreateResource(global::System.Guid ID)
        {
            Resource resource = new Resource();
            resource.ID = ID;
            return resource;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Appointment> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                if ((value != null))
                {
                    this._Appointments = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Appointment> _Appointments = new global::System.Collections.ObjectModel.Collection<Appointment>();
    }
    /// <summary>
    /// There are no comments for DevExpress.Calendar.Model.Appointment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Appointment
    {
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="isAllDay">Initial value of IsAllDay.</param>
        /// <param name="label">Initial value of Label.</param>
        /// <param name="completionStatus">Initial value of CompletionStatus.</param>
        /// <param name="start">Initial value of Start.</param>
        /// <param name="finish">Initial value of Finish.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="itemType">Initial value of ItemType.</param>
        /// <param name="appointmentType">Initial value of AppointmentType.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Appointment CreateAppointment(global::System.Guid ID, bool isAllDay, int label, int completionStatus, global::System.DateTime start, global::System.DateTime finish, int status, int itemType, int appointmentType)
        {
            Appointment appointment = new Appointment();
            appointment.ID = ID;
            appointment.IsAllDay = isAllDay;
            appointment.Label = label;
            appointment.CompletionStatus = completionStatus;
            appointment.Start = start;
            appointment.Finish = finish;
            appointment.Status = status;
            appointment.ItemType = itemType;
            appointment.AppointmentType = appointmentType;
            return appointment;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IsAllDay in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAllDay
        {
            get
            {
                return this._IsAllDay;
            }
            set
            {
                this.OnIsAllDayChanging(value);
                this._IsAllDay = value;
                this.OnIsAllDayChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAllDay;
        partial void OnIsAllDayChanging(bool value);
        partial void OnIsAllDayChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Label in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Label;
        partial void OnLabelChanging(int value);
        partial void OnLabelChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Recurrence in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Recurrence
        {
            get
            {
                return this._Recurrence;
            }
            set
            {
                this.OnRecurrenceChanging(value);
                this._Recurrence = value;
                this.OnRecurrenceChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Recurrence;
        partial void OnRecurrenceChanging(string value);
        partial void OnRecurrenceChanged();
        /// <summary>
        /// There are no comments for Property Reminder in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reminder
        {
            get
            {
                return this._Reminder;
            }
            set
            {
                this.OnReminderChanging(value);
                this._Reminder = value;
                this.OnReminderChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reminder;
        partial void OnReminderChanging(string value);
        partial void OnReminderChanged();
        /// <summary>
        /// There are no comments for Property CompletionStatus in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CompletionStatus
        {
            get
            {
                return this._CompletionStatus;
            }
            set
            {
                this.OnCompletionStatusChanging(value);
                this._CompletionStatus = value;
                this.OnCompletionStatusChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CompletionStatus;
        partial void OnCompletionStatusChanging(int value);
        partial void OnCompletionStatusChanged();
        /// <summary>
        /// There are no comments for Property Start in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Start
        {
            get
            {
                return this._Start;
            }
            set
            {
                this.OnStartChanging(value);
                this._Start = value;
                this.OnStartChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
        /// <summary>
        /// There are no comments for Property Finish in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Finish
        {
            get
            {
                return this._Finish;
            }
            set
            {
                this.OnFinishChanging(value);
                this._Finish = value;
                this.OnFinishChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Finish;
        partial void OnFinishChanging(global::System.DateTime value);
        partial void OnFinishChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property ItemType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ItemType
        {
            get
            {
                return this._ItemType;
            }
            set
            {
                this.OnItemTypeChanging(value);
                this._ItemType = value;
                this.OnItemTypeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ItemType;
        partial void OnItemTypeChanging(int value);
        partial void OnItemTypeChanged();
        /// <summary>
        /// There are no comments for Property AppointmentType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AppointmentType
        {
            get
            {
                return this._AppointmentType;
            }
            set
            {
                this.OnAppointmentTypeChanging(value);
                this._AppointmentType = value;
                this.OnAppointmentTypeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AppointmentType;
        partial void OnAppointmentTypeChanging(int value);
        partial void OnAppointmentTypeChanged();
        /// <summary>
        /// There are no comments for Property AssignedTo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> AssignedTo
        {
            get
            {
                return this._AssignedTo;
            }
            set
            {
                this.OnAssignedToChanging(value);
                this._AssignedTo = value;
                this.OnAssignedToChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _AssignedTo;
        partial void OnAssignedToChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnAssignedToChanged();
        /// <summary>
        /// There are no comments for Resource in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Resource Resource
        {
            get
            {
                return this._Resource;
            }
            set
            {
                this._Resource = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Resource _Resource;
    }
}
